/**
 * Create a Lookalike Audience seeded from one of the dealer's existing
 * Custom Audiences.
 *
 * Request body: { audienceId: string (our internal id), country?: string,
 *   ratio?: number (0.01-0.10) }
 *
 * On success: creates a new MetaCustomAudience row of kind
 * `lookalike_of_<source_kind>` linking to Meta's new audience ID.
 */
import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getEffectiveDealerContext } from "@/lib/impersonation";
import { createLookalikeAudience } from "@/lib/metaAudiences";
import { decryptToken } from "@/lib/meta";

export const maxDuration = 30;

export async function POST(request: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  const ctx = await getEffectiveDealerContext();
  if (!ctx.effectiveDealerId) {
    return NextResponse.json({ error: "no_dealer" }, { status: 403 });
  }

  let body: { audienceId?: string; country?: string; ratio?: number };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "invalid_body" }, { status: 400 });
  }

  if (!body.audienceId || typeof body.audienceId !== "string") {
    return NextResponse.json({ error: "audienceId_required" }, { status: 400 });
  }

  const country = body.country ?? "US";
  const ratio = body.ratio ?? 0.02;
  if (typeof ratio !== "number" || ratio < 0.01 || ratio > 0.1) {
    return NextResponse.json({ error: "ratio_out_of_range" }, { status: 400 });
  }

  // Lookup + verify the audience belongs to the calling dealer.
  const source = await prisma.metaCustomAudience.findUnique({
    where: { id: body.audienceId },
  });
  if (!source || source.dealerId !== ctx.effectiveDealerId) {
    return NextResponse.json({ error: "audience_not_found" }, { status: 404 });
  }
  if (source.audienceKind.startsWith("lookalike_of_")) {
    return NextResponse.json(
      { error: "cannot_lookalike_a_lookalike" },
      { status: 400 }
    );
  }

  const dealer = await prisma.dealer.findUnique({
    where: { id: ctx.effectiveDealerId },
    select: { metaAccessToken: true, slug: true },
  });
  if (!dealer?.metaAccessToken) {
    return NextResponse.json({ error: "meta_not_connected" }, { status: 400 });
  }
  const accessToken = decryptToken(dealer.metaAccessToken);

  const lookalikeName = `Lookalike (${(ratio * 100).toFixed(0)}%, ${country}) of ${source.name}`;

  try {
    const created = await createLookalikeAudience({
      adAccountId: source.metaAdAccountId,
      name: lookalikeName,
      description: `Auto-generated by CIA Feeds. Seed: ${source.name}.`,
      originAudienceId: source.metaAudienceId,
      country,
      ratio,
      accessToken,
    });

    const row = await prisma.metaCustomAudience.create({
      data: {
        dealerId: ctx.effectiveDealerId,
        audienceKind: `lookalike_of_${source.audienceKind}`,
        sourceListingId: source.sourceListingId,
        sourceVehicleId: source.sourceVehicleId,
        metaAudienceId: created.id,
        metaAdAccountId: source.metaAdAccountId,
        name: lookalikeName,
        description: `Lookalike seeded from ${source.name}.`,
        lastRefreshedAt: new Date(),
      },
    });

    return NextResponse.json({ ok: true, audienceId: row.id });
  } catch (err) {
    const message = err instanceof Error ? err.message : "lookalike_failed";
    return NextResponse.json({ error: message }, { status: 400 });
  }
}
