ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "trim" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "drivetrain" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "transmission" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "fuelType" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "msrp" DOUBLE PRECISION;
