ALTER TABLE "Dealer" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Dealer" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "Dealer" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
