import { prisma } from "@/lib/prisma";
import { decryptToken, graphFetch } from "@/lib/meta";
import { createHash, randomUUID } from "crypto";

/**
 * Send a Meta Conversions API event server-side.
 *
 * Extended in May 2026 (Option 1 retargeting build) to support:
 *   - eventID  for dedup with the client-side Pixel ViewContent
 *   - user_data with hashed email/phone (sha256 hex) + fbp/fbc browser
 *     identifiers + client IP + user-agent. Meta uses these for
 *     identity resolution; without them, audience match rates drop
 *     significantly.
 *   - event_source_url for Meta's content matching against catalog URLs.
 *
 * Dedup contract with the Pixel:
 *   The client should fire fbq("track", "ViewContent", data, { eventID })
 *   using the same `eventId` we pass here. Meta will keep the more
 *   complete event (usually the server-side one) and drop the duplicate.
 *
 * Hashing: Meta requires SHA-256 hex (lowercase) for email/phone, with
 * normalization (lowercase, strip non-digits for phones). All hashing
 * happens server-side here so plaintext PII never leaves our process.
 */
export interface MetaUserData {
  /** Plaintext email; will be lowercased + hashed before send. */
  email?: string | null;
  /** Plaintext phone; non-digits stripped + hashed before send. */
  phone?: string | null;
  /** Facebook browser ID cookie (`_fbp`), as-is, no hashing. */
  fbp?: string | null;
  /** Facebook click ID cookie (`_fbc`), as-is, no hashing. */
  fbc?: string | null;
  /** Visitor's IP address (from x-forwarded-for or req IP). */
  clientIpAddress?: string | null;
  /** Visitor's User-Agent string. */
  clientUserAgent?: string | null;
  /** External ID (e.g. our own session/visitor cookie). Not hashed. */
  externalId?: string | null;
}

export interface SendMetaEventOptions {
  pixelId: string;
  eventName: string;
  data?: Record<string, unknown>;
  dealerId: string;
  /**
   * Dedup key shared with the client-side Pixel event. Generated by
   * caller (e.g. crypto.randomUUID()). If omitted, we generate one
   * here but the caller won't be able to set the same one on the
   * Pixel side, so dedup won't work.
   */
  eventId?: string;
  /** Browser/user identifiers and hashed PII. */
  userData?: MetaUserData;
  /** Full URL of the page that triggered the event. */
  eventSourceUrl?: string;
}

function sha256Hex(input: string): string {
  return createHash("sha256").update(input).digest("hex");
}

function normalizeAndHashEmail(email: string): string {
  return sha256Hex(email.trim().toLowerCase());
}

function normalizeAndHashPhone(phone: string): string {
  // Per Meta: digits only, no +/spaces/hyphens, then sha256.
  return sha256Hex(phone.replace(/\D/g, ""));
}

function buildUserDataPayload(u: MetaUserData): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  if (u.email) out.em = [normalizeAndHashEmail(u.email)];
  if (u.phone) out.ph = [normalizeAndHashPhone(u.phone)];
  if (u.fbp) out.fbp = u.fbp;
  if (u.fbc) out.fbc = u.fbc;
  if (u.clientIpAddress) out.client_ip_address = u.clientIpAddress;
  if (u.clientUserAgent) out.client_user_agent = u.clientUserAgent;
  if (u.externalId) out.external_id = [sha256Hex(u.externalId)];
  return out;
}

export async function sendMetaEvent(opts: SendMetaEventOptions): Promise<void> {
  const {
    pixelId,
    eventName,
    data,
    dealerId,
    eventId,
    userData,
    eventSourceUrl,
  } = opts;

  const dealer = await prisma.dealer.findUnique({
    where: { id: dealerId },
    select: { metaAccessToken: true, metaPixelId: true },
  });

  if (!dealer) return;
  if (pixelId !== dealer.metaPixelId) return;
  if (!dealer.metaAccessToken && !process.env.META_PUBLIC_ACCESS_TOKEN) return;

  const eventPayload: Record<string, unknown> = {
    event_name: eventName,
    event_time: Math.floor(Date.now() / 1000),
    action_source: "website",
    event_id: eventId ?? randomUUID(),
    custom_data: data ?? {},
  };
  if (eventSourceUrl) eventPayload.event_source_url = eventSourceUrl;
  if (userData) {
    const ud = buildUserDataPayload(userData);
    if (Object.keys(ud).length > 0) eventPayload.user_data = ud;
  }

  const payload = { data: [eventPayload] };

  const token = dealer.metaAccessToken
    ? decryptToken(dealer.metaAccessToken)
    : process.env.META_PUBLIC_ACCESS_TOKEN!;

  const res = await graphFetch(
    `/${encodeURIComponent(pixelId)}/events`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    },
    token
  );

  if (!res.ok) {
    const errBody = await res.text();
    console.error("[metaTrack] Meta CAPI error:", res.status, errBody);
  }
}

/**
 * Read Meta's browser identifier cookies from a Next.js cookies() bag.
 * Both are set by the Pixel itself; if the Pixel hasn't fired on this
 * visitor yet, both return null and Meta falls back to IP+UA matching.
 *
 * `_fbc` is only present if the visitor arrived via a Facebook ad click
 * (it encodes the click ID), so null is normal for organic traffic.
 */
export function readMetaCookies(cookies: {
  get: (name: string) => { value: string } | undefined;
}): { fbp: string | null; fbc: string | null } {
  return {
    fbp: cookies.get("_fbp")?.value ?? null,
    fbc: cookies.get("_fbc")?.value ?? null,
  };
}
