ALTER TABLE "Dealer" ADD COLUMN IF NOT EXISTS "metaAccessToken" TEXT;
ALTER TABLE "Dealer" ADD COLUMN IF NOT EXISTS "metaBusinessId" TEXT;
ALTER TABLE "Dealer" ADD COLUMN IF NOT EXISTS "metaCatalogId" TEXT;
ALTER TABLE "Dealer" ADD COLUMN IF NOT EXISTS "metaFeedId" TEXT;
